In [1]:
import pandas as pd
csv = pd.read_csv("./overview-of-recordings-processed.csv")

In [94]:
for i in range(0,len(csv)):
    if csv.iloc[i]["file_name"] == "1249120_44142156_69073946.wav":
        print(csv.iloc[i]["prompt"], csv.iloc[i]["phrase"])

Surgery department My knee doesn't want to bend well.


In [8]:
spTrain = pd.read_csv("./speech_based_features.csv")
spTest =pd.read_csv("./speech_based_features_test.csv")
spVali = pd.read_csv("./speech_based_features_validate.csv")

In [55]:
features = ["min_pitch", "max_pitch", "mean_pitch", "sd_pitch", "min_intensity", "max_intensity", "mean_intensity",
           "sd_intensity", "jitter", "shimmer", "hnr", "speakingRate"]

In [57]:
for each in keyList:
    features.append(each)
    
features

['min_pitch',
 'max_pitch',
 'mean_pitch',
 'sd_pitch',
 'min_intensity',
 'max_intensity',
 'mean_intensity',
 'sd_intensity',
 'jitter',
 'shimmer',
 'hnr',
 'speakingRate',
 'LS',
 'TO',
 'VBN',
 "''",
 'WP',
 'UH',
 'VBG',
 'JJ',
 'VBZ',
 '--',
 'VBP',
 'NN',
 'DT',
 'PRP',
 ':',
 'WP$',
 'NNPS',
 'PRP$',
 'WDT',
 '(',
 ')',
 '.',
 ',',
 '``',
 '$',
 'RB',
 'RBR',
 'RBS',
 'VBD',
 'IN',
 'FW',
 'RP',
 'JJR',
 'JJS',
 'PDT',
 'MD',
 'VB',
 'WRB',
 'NNP',
 'EX',
 'NNS',
 'SYM',
 'CC',
 'CD',
 'POS']

In [25]:
spFinal = spTrain.append(spTest, ignore_index=True)
spFinal = spFinal.append(spVali, ignore_index=True)

In [26]:
spFinal.rename(columns={'voice_ID':'file_name'},inplace=True)

In [39]:
spFinal = spFinal.sort_values(by=['file_name'])
df = df.sort_values(by=['file_name'])
spFinal = spFinal.reset_index(drop=True)
df = df.reset_index(drop=True)

In [43]:
spFinal1 = spFinal.drop(['file_name', 'prompt'], axis=1)
final = spFinal1.join(df)

In [44]:
final

min_pitch   max_pitch  mean_pitch    sd_pitch  min_intensity  \
0     107.206950  597.327842  185.976781  146.558857      53.156259   
1     106.127969  591.110113  120.712913   35.324474      52.726798   
2     101.064519  598.581327  170.033275  137.282865      49.108919   
3     104.347559  567.093190  130.185093   56.856801      52.212186   
4      94.580900  599.548579  150.909065  110.539039      51.399745   
...          ...         ...         ...         ...            ...   
6656  114.448109  191.475944  148.660352   22.021310      20.842657   
6657  101.827281  196.893966  140.994470   17.624729      25.437057   
6658  102.911288  194.157518  137.383134   16.729277      22.759998   
6659   77.235202  592.787480  167.974645   49.054245      21.559203   
6660  111.111462  573.868467  152.418897   60.741012      26.646793   

      max_intensity  mean_intensity  sd_intensity    jitter   shimmer  ...  \
0         83.417009       68.793224      9.651903  0.012259  0.120073  ...   
1         83.808242       70.056738      9.236341  0.009400  0.091235  ...   
2         78.738312       63.987175      8.870147  0.013357  0.189878  ...   
3         85.998126       72.037190      9.169391  0.008287  0.084389  ...   
4         82.189346       71.726032      8.404453  0.009881  0.146973  ...   
...             ...             ...           ...       ...       ...  ...   
6656      82.548419       58.601974     20.014081  0.007743  0.130359  ...   
6657      86.084674       62.966509     16.128682  0.008811  0.107834  ...   
6658      82.177099       64.932179     15.295624  0.007887  0.065544  ...   
6659      87.268730       61.921015     17.876592  0.008683  0.087514  ...   
6660      81.729379       60.238352     16.923720  0.007917  0.112981  ...   

      NNP  EX  NNS  SYM  CC  CD  POS                       file_name  \
0       0   0    1    0   0   0    0  1249120_13842059_104469105.wav   
1       0   0    1    0   0   0    0  1249120_13842059_105045085.wav   
2       0   0    0    0   0   0    0   1249120_13842059_11964685.wav   
3       0   0    0    0   0   0    0   1249120_13842059_12420758.wav   
4       0   0    0    0   0   0    0   1249120_13842059_13041979.wav   
...   ...  ..  ...  ...  ..  ..  ...                             ...   
6656    0   0    0    0   0   0    0    1249120_6338946_95779210.wav   
6657    1   0    0    0   0   0    0    1249120_6338946_97962298.wav   
6658    0   0    1    0   1   0    0    1249120_6338946_98107593.wav   
6659    0   0    0    0   2   0    0    1249120_6338946_99675257.wav   
6660    0   0    0    0   0   0    0    1249120_6338946_99780649.wav   

                                                 phrase              prompt  
0                     I have a painful cramp in my feet  Surgery department  
1         The pain feels like it's right below the skin               Other  
2                                      I feel suicidal.       Mental health  
3     I feel a sharp pain in my ankle joint when I s...               Other  
4                          My shoulder hurts me so much  Surgery department  
...                                                 ...                 ...  
6656                             my ankle is hurting me               Other  
6657  I can't walk because i have a great Surgery de...  Surgery department  
6658  When I tried to be warm and wear more clothes ...               Other  
6659  I've always been very active but now I just do...               Other  
6660                           I wake up at night Other               Other  

[6661 rows x 60 columns]

In [2]:
csv.head(1)

audio_clipping  audio_clipping:confidence background_noise_audible  \
0    no_clipping                        1.0              light_noise   

   background_noise_audible:confidence  overall_quality_of_the_audio  \
0                                  1.0                          3.33   

     quiet_speaker  quiet_speaker:confidence  speaker_id  \
0  audible_speaker                       1.0    43453425   

                                       file_download  \
0  https://ml.sandbox.cf3.us/cgi-bin/index.cgi?do...   

                       file_name                           phrase  \
0  1249120_43453425_58166571.wav  When I remember her I feel down   

          prompt  writer_id  
0  Mental health   21665495

In [ ]:
data = csv[["phrase", "prompt"]]
isUnique = set()
for i in range(0, len(data)):
    isUnique.add((data.iloc[i][0],data.iloc[i][1]))

isUniqueList = list(isUnique)
final = pd.DataFrame(isUniqueList, columns = ['phrase' , 'prompt'])
final

In [86]:
import nltk
from nltk.data import load
tagdict = load('help/tagsets/upenn_tagset.pickle')
keyList = []
for key in tagdict.keys():
    keyList.append(key)

skeleton_dict = {key: 0 for key in keyList}
len(keyList)

45

Option 1 : Use unique text to extract features

In [ ]:
import numpy as np
rows_list = []
for index in range(len(final)):
    #file_name = final.iloc[index]["file_name"]
    phrase = final.iloc[index]["phrase"]
    prompt = final.iloc[index]["prompt"]
    
    tokens = nltk.word_tokenize(phrase)
    tagged = nltk.pos_tag(tokens)
    skeleton_dict_copy = skeleton_dict.copy()
    for i in range(len(tagged)):
        skeleton_dict_copy[tagged[i][1]] = skeleton_dict_copy[tagged[i][1]]+1
    #skeleton_dict_copy["file_name"] = file_name
    skeleton_dict_copy["phrase"] = phrase
    skeleton_dict_copy["prompt"] = prompt
    rows_list.append(skeleton_dict_copy)
df = pd.DataFrame(rows_list)

Option 2: use all text (including duplicate text) to extract features

In [4]:
import numpy as np
rows_list = []
from tqdm import tqdm
t = tqdm(total=len(csv))
for index in range(len(csv)):
    file_name = csv.iloc[index]["file_name"]
    phrase = csv.iloc[index]["phrase"]
    prompt = csv.iloc[index]["prompt"]
    
    tokens = nltk.word_tokenize(phrase)
    tagged = nltk.pos_tag(tokens)
    skeleton_dict_copy = skeleton_dict.copy()
    for i in range(len(tagged)):
        skeleton_dict_copy[tagged[i][1]] = skeleton_dict_copy[tagged[i][1]]+1
    skeleton_dict_copy["file_name"] = file_name
    skeleton_dict_copy["phrase"] = phrase
    skeleton_dict_copy["prompt"] = prompt
    rows_list.append(skeleton_dict_copy)
    t.update(1)
df = pd.DataFrame(rows_list)

100%|████████████████████████████████████████████████████████████████████████████▉| 6656/6661 [00:27<00:00, 261.87it/s]

In [5]:
df

LS  TO  VBN  ''  WP  UH  VBG  JJ  VBZ  --  ...  NNP  EX  NNS  SYM  CC  \
0      0   0    0   0   0   0    0   0    0   0  ...    0   0    0    0   0   
1      0   0    0   0   0   0    1   1    0   0  ...    0   0    1    0   0   
2      0   0    0   0   0   0    0   1    1   0  ...    0   1    0    0   0   
3      0   0    2   0   0   0    0   1    3   0  ...    0   0    0    0   3   
4      0   0    0   0   0   0    1   0    0   0  ...    0   0    1    0   0   
...   ..  ..  ...  ..  ..  ..  ...  ..  ...  ..  ...  ...  ..  ...  ...  ..   
6656   0   0    0   0   0   0    0   0    0   0  ...    0   0    2    0   0   
6657   0   0    0   0   0   0    0   0    0   0  ...    0   0    0    0   0   
6658   0   0    0   0   0   0    0   0    0   0  ...    0   0    1    0   0   
6659   0   0    0   0   0   0    0   1    1   0  ...    0   0    0    0   0   
6660   0   0    0   0   0   0    0   1    0   0  ...    0   0    0    0   0   

      CD  POS                      file_name  \
0      0    0  1249120_43453425_58166571.wav   
1      0    0  1249120_43719934_43347848.wav   
2      0    0  1249120_43719934_53187202.wav   
3      0    0  1249120_31349958_55816195.wav   
4      0    0  1249120_43719934_82524191.wav   
...   ..  ...                            ...   
6656   1    0  1249120_14353703_45949288.wav   
6657   0    0  1249120_15004831_26452554.wav   
6658   0    0  1249120_15004831_64958100.wav   
6659   0    0  1249120_15830408_92962528.wav   
6660   0    0  1249120_15004831_80093096.wav   

                                                 phrase              prompt  
0                       When I remember her I feel down       Mental health  
1     When I carry heavy things I feel like breaking...          Skin issue  
2             there is too much pain when i move my arm   Internal medicine  
3     My son had his lip pierced and it is swollen a...  Surgery department  
4                My muscles in my lower back are aching  Surgery department  
...                                                 ...                 ...  
6656  I feel a burning sensation in my guts about 2 ...   Internal medicine  
6657     I have a split on my thumb that will not heal.  Surgery department  
6658                I feel a lot of pain in the joints.               Other  
6659        The area around my heart doesn't feel good.   Internal medicine  
6660                  I complain alot with skin allergy          Skin issue  

[6661 rows x 48 columns]

100%|█████████████████████████████████████████████████████████████████████████████| 6661/6661 [00:40<00:00, 261.87it/s]

In [85]:
#df.to_csv("duplicateContainText.csv")
#df.to_csv("uniqueText.csv")
final.to_csv("speechXtext.csv")

In [79]:
# Option 1
#train = df[0:530]
#test = df[530:]

# Option 2
#train = df[0:4661]
#test = df[4661:]

# Option 3
train = final[0:4661]
test = final[4661:]
train = train.dropna()
test = test.dropna()

In [80]:
#train_textX=train[keyList]
train_textX=train[features]
train_texty=train["prompt"]
train_textX = np.array(train_textX.values.tolist())
train_texty = np.array(train_texty.tolist())

In [81]:
from sklearn import multiclass
from sklearn import tree
from sklearn.svm import LinearSVC

In [82]:
classifier = multiclass.OneVsRestClassifier(tree.DecisionTreeClassifier())
classifier.fit(train_textX,train_texty)

OneVsRestClassifier(estimator=DecisionTreeClassifier(class_weight=None,
                                                     criterion='gini',
                                                     max_depth=None,
                                                     max_features=None,
                                                     max_leaf_nodes=None,
                                                     min_impurity_decrease=0.0,
                                                     min_impurity_split=None,
                                                     min_samples_leaf=1,
                                                     min_samples_split=2,
                                                     min_weight_fraction_leaf=0.0,
                                                     presort=False,
                                                     random_state=None,
                                                     splitter='best'),
                    n_jobs=None)

In [83]:
#test_textX=test[keyList]
test_textX=test[features]
test_texty=test["prompt"]
test_textX = np.array(test_textX.values.tolist())
test_texty = np.array(test_texty.tolist())

In [84]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix
predict_texty = classifier.predict(test_textX)
accuracy=accuracy_score(test_texty, predict_texty)
f1=f1_score(test_texty, predict_texty, average="weighted")
cm=confusion_matrix(test_texty, predict_texty)
print(accuracy)
print(f1)
print(cm)

0.85
0.848309991856775
[[286  10   6  10  16  72]
 [  1  39   1   5   2  13]
 [  0   2 174   4   5  34]
 [  4   1   1 287  11  28]
 [  5   2   0   4 210  38]
 [  7   4   4   7   3 704]]


To check which text has pos tag "POS". Can replace "POS" with other pos tags.

In [ ]:
classes = ["Mental health", "Skin issue", "Internal medicine", "Surgery department", "Other", "Neurology"]
tmpDF = df[df["POS"]>0]
tmpDict = {}
for index in range(len(classes)):
    tmpDict[classes[index]] = len(tmpDF[tmpDF["prompt"]==classes[index]])
    
tmpDF["phrase"]

Extract pos tags from a single text sentence

In [ ]:
string = "My chest Skin issue breaks out and never clears up."
ts = nltk.word_tokenize(string)
td = nltk.pos_tag(ts)
print(td)
sdc = skeleton_dict.copy()
for i in range(len(td)):
    sdc[td[i][1]] = sdc[td[i][1]]+1
temp = {}
for key in sdc.keys():
    if sdc[key]>0:
        temp[key] = sdc[key]
        
temp

In [92]:
import nltk
from nltk.data import load
tagdict = load('help/tagsets/upenn_tagset.pickle')
keyList = []
for key in tagdict.keys():
    keyList.append(key)

skeleton_dict = {key: 0 for key in keyList}
string = "My chest Skin issue breaks out and never clears up."
ts = nltk.word_tokenize(string)
td = nltk.pos_tag(ts)

sdc = skeleton_dict.copy()
for i in range(len(td)):
    sdc[td[i][1]] = sdc[td[i][1]]+1

list(sdc.items())

[('LS', 0),
 ('TO', 0),
 ('VBN', 0),
 ("''", 0),
 ('WP', 0),
 ('UH', 0),
 ('VBG', 0),
 ('JJ', 0),
 ('VBZ', 2),
 ('--', 0),
 ('VBP', 0),
 ('NN', 1),
 ('DT', 0),
 ('PRP', 0),
 (':', 0),
 ('WP$', 0),
 ('NNPS', 0),
 ('PRP$', 1),
 ('WDT', 0),
 ('(', 0),
 (')', 0),
 ('.', 1),
 (',', 0),
 ('``', 0),
 ('$', 0),
 ('RB', 1),
 ('RBR', 0),
 ('RBS', 0),
 ('VBD', 0),
 ('IN', 0),
 ('FW', 0),
 ('RP', 2),
 ('JJR', 0),
 ('JJS', 1),
 ('PDT', 0),
 ('MD', 0),
 ('VB', 0),
 ('WRB', 0),
 ('NNP', 1),
 ('EX', 0),
 ('NNS', 0),
 ('SYM', 0),
 ('CC', 1),
 ('CD', 0),
 ('POS', 0)]